### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Fs02** [marmelab/aor-simple-graphql-client#38]
Hi, thanks for the awesome work.

I'm trying to follow the readme and I'm stuck with this error when loading the page:
```
buildFieldList.js?7695:69 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at Array.find (native)
    at eval (eval at <anonymous> (http://localhost:3000/webpack/development/webpack-bundle-949b87a75a60b8b8d5c9.js:9388:1), <anonymous>:69:34)
    at Array.map (native)
    at buildFieldListFromList (eval at <anonymous> (http://localhost:3000/webpack/development/webpack-bundle-949b87a75a60b8b8d5c9.js:9388:1), <anonymous>:64:8)
    at eval (eval at <anonymous> (http://localhost:3000/webpack/development/webpack-bundle-949b87a75a60b8b8d5c9.js:9388:1), <anonymous>:74:37)
    at Array.map (native)
    at buildFieldListFromList (eval at <anonymous> (http://localhost:3000/webpack/development/webpack-bundle-949b87a75a60b8b8d5c9.js:9388:1), <anonymous>:64:8)
    at eval (eval at <anonymous> (http://localhost:3000/webpack/development/webpack-bundle-949b87a75a60b8b8d5c9.js:9388:1), <anonymous>:74:37)
    at Array.map (native)
    at buildFieldListFromList (eval at <anonymous> (http://localhost:3000/webpack/development/webpack-bundle-949b87a75a60b8b8d5c9.js:9388:1), <anonymous>:64:8)
```

This is my admin page:
```
import React, { Component } from 'react';
import { buildApolloClient } from 'aor-simple-graphql-client';

import { Admin, Resource } from 'admin-on-rest';
import { Delete } from 'admin-on-rest/lib/mui';

import { CustomerList } from './customers';

class AdminPage extends Component {
  constructor() {
    super();
    this.state = { restClient: null };
  }
  
  componentDidMount() {
    buildApolloClient({ clientOptions: { uri: '/queries' } })
      .then(restClient => this.setState({ restClient }));
  }

  render() {
    if (!this.state.restClient) {
        return <div>Loading</div>;
    }

    return (
      <Admin restClient={this.state.restClient}>
        <Resource name='Customer' list={CustomerList} />
      </Admin>
    );
  }
}

export default AdminPage;
```

customer page:
```
import React from 'react';
import { List, Datagrid, TextField } from 'admin-on-rest';

export const CustomerList = (props) => (
  <List {...props}>
    <Datagrid>
      <TextField source="id" />
    </Datagrid>
  </List>
);
```

GraphQL query and it's result:
```
// query
{
  getPageOfCustomers(page: 0, perPage: 10, sortField: "", sortOrder: "", filter: "") {
    items {
      id
    }
    totalCount
  }
}
// response
{
  "data": {
    "getPageOfCustomers": {
      "items": [
        {
          "id": "1"
        }
      ],
      "totalCount": 1
    }
  }
}
```

**Comment by dervos** [comment]
Hey, I had the same issue. I resolved it by adding the following `introspectionOptions`:
```JSX
// file: introspectionOptions.js
export default {
  ignoreSubObjects: true,
};

```
and adding it to the build:
```JSX
// file: client.js
export default () =>
  buildApolloClient({
    client,
    flavor,
    introspection: introspectionOptions,
  });
```

**Comment by djhi** [comment]
I was certain I set it false by default...

**Comment by Fs02** [comment]
Thanks, it's works!
